name: Deploy to EC2

on:
  push:
    branches:
      - master  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=yes $EC2_USER@$EC2_HOST "ls -la" 

#  ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "cd /home/ec2-user/notes/MeGraphServer && git pull & npm start"

